"""The middleware stack, rendered once and described the same way everywhere.

`render_middleware_compose` is what the personal edition writes into the home. The
scaffold's generated project keeps its own `docker-compose.yml` — copied byte for byte,
environment-driven, and carrying an optional console profile the edition has no use for —
so it is not rendered from here. What must not drift is the four services themselves:
images, healthchecks, published container ports and environment keys. These tests pin the
renderer, and pin it against the scaffold's template.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from pneuma_knowledge_service.infra.compose import (
    DATA_PATHS,
    PORT_KEYS,
    render_middleware_compose,
)

ROOT = Path(__file__).resolve().parents[3]
SCAFFOLD_COMPOSE = ROOT / "scaffold" / "templates" / "docker-compose.yml"

MIDDLEWARE = ("postgres", "qdrant", "meilisearch", "rustfs")

PORTS = {
    "pg": 25432,
    "qdrant": 26333,
    "qdrant_grpc": 26334,
    "meili": 27700,
    "rustfs": 29000,
    "rustfs_console": 29001,
}

SECRETS = {
    "pg_password": "pg-secret",
    "meili_key": "meili-secret",
    "rustfs_access_key": "access-key",
    "rustfs_secret_key": "secret-key",
}


def _render(**overrides) -> dict:
    kwargs = {"project_name": "pkc-home", "ports": PORTS, **SECRETS}
    kwargs.update(overrides)
    return yaml.safe_load(render_middleware_compose(**kwargs))


def _container_ports(entries: list[str]) -> list[str]:
    return [entry.rsplit(":", 1)[-1] for entry in entries]


def test_it_renders_exactly_the_four_middleware_services():
    document = _render()
    assert document["name"] == "pkc-home"
    assert list(document["services"]) == list(MIDDLEWARE)


def test_every_published_port_is_the_callers_and_binds_loopback_only():
    document = _render()
    published = [
        entry
        for service in document["services"].values()
        for entry in service["ports"]
    ]
    assert all(entry.startswith("127.0.0.1:") for entry in published)
    assert sorted(int(entry.split(":")[1]) for entry in published) == sorted(PORTS.values())


def test_a_missing_port_is_refused_rather_than_defaulted():
    with pytest.raises(ValueError) as refusal:
        render_middleware_compose(
            project_name="pkc-home",
            ports={key: 20000 for key in PORT_KEYS if key != "meili"},
            **SECRETS,
        )
    assert "meili" in str(refusal.value)


def test_without_a_data_dir_the_four_named_volumes_are_declared():
    document = _render()
    assert set(document["volumes"]) == {name for _, name in DATA_PATHS.values()}
    for service in MIDDLEWARE:
        container_path, volume_name = DATA_PATHS[service]
        assert document["services"][service]["volumes"] == [f"{volume_name}:{container_path}"]


def test_with_a_data_dir_each_service_bind_mounts_its_own_subdirectory():
    document = _render(data_dir="/Users/someone/.pkc/data")
    assert "volumes" not in document
    for service in MIDDLEWARE:
        container_path, _volume = DATA_PATHS[service]
        assert document["services"][service]["volumes"] == [
            f"/Users/someone/.pkc/data/{service}:{container_path}"
        ]


def test_a_subnet_pins_the_default_network_and_is_absent_without_one():
    assert "networks" not in _render()
    document = _render(subnet="10.140.7.0/24")
    assert document["networks"]["default"]["ipam"]["config"] == [{"subnet": "10.140.7.0/24"}]


def test_the_secrets_are_written_where_each_service_reads_them():
    document = _render()
    services = document["services"]
    assert services["postgres"]["environment"]["POSTGRES_PASSWORD"] == "pg-secret"
    assert services["meilisearch"]["environment"]["MEILI_MASTER_KEY"] == "meili-secret"
    assert services["rustfs"]["environment"]["RUSTFS_ACCESS_KEY"] == "access-key"
    assert services["rustfs"]["environment"]["RUSTFS_SECRET_KEY"] == "secret-key"


@pytest.mark.skipif(not SCAFFOLD_COMPOSE.is_file(), reason="scaffold template not present")
def test_the_scaffolds_four_services_and_the_rendered_ones_stay_equivalent():
    """The one guard against two descriptions of the same stack drifting apart.

    The scaffold's file is copied verbatim into a generated project, so it cannot be
    rendered from the library without changing the generated bytes. Equivalence is asserted
    instead: same images, same healthchecks, same container ports, same environment keys.
    A deliberate change to either must be made in both, and this test is where that is
    noticed.
    """
    scaffold = yaml.safe_load(SCAFFOLD_COMPOSE.read_text(encoding="utf-8"))["services"]
    rendered = _render()["services"]

    for service in MIDDLEWARE:
        theirs, ours = scaffold[service], rendered[service]
        assert theirs["image"] == ours["image"], service
        assert theirs["healthcheck"]["test"] == ours["healthcheck"]["test"], service
        assert _container_ports(theirs["ports"]) == _container_ports(ours["ports"]), service
        assert sorted(theirs.get("environment", {})) == sorted(ours.get("environment", {})), service
        assert theirs.get("command") == ours.get("command"), service
        # The mount point inside the container is the service's state, whatever the host
        # side happens to be.
        assert [entry.split(":", 1)[1] for entry in theirs["volumes"]] == [
            entry.rsplit(":", 1)[-1] for entry in ours["volumes"]
        ], service
