"""Is this `pkc` talking to the library it is standing in?

`app.py` has asked that question since the scaffold existed (`isolation_problems`): every
connection target must land on the ports the generator probed free and wrote into the
project's `.env`, and a configuration that drifted toward some other stack on the machine is
refused before anything connects. `pkc` had no equivalent, and it is the command a coding
agent actually runs — so a project whose `.env` stated its ports but not its DSNs sent every
`pkc` command to the FRAMEWORK's own development stack (15432 / 16333 / 17700) and, with a
matching embedding dimension, would have written into the developer's own library.

The guard is the same one, asked from the other side. A scaffold project announces itself by
the `PNEUMA_APP_*` ports in its `.env`; where those are stated, the resolved `Settings` must
agree with them. Nothing else is a project, so nothing else is checked: `pkc` inside the
framework repository, inside a container, or against a hand-assembled deployment behaves
exactly as it did before this file existed.
"""

from __future__ import annotations

import os
from collections.abc import Mapping
from pathlib import Path

#: The project's own `.env`, read the way the shim reads it — so a `pkc` invoked directly in
#: a project directory is judged by the same file as one invoked through the shim.
ENV_FILENAME = ".env"

#: Which `PNEUMA_APP_*` port a settings field must land on, and what to call it in a refusal.
#: The tuple IS the check: a fifth service is a row here.
_PORTED: tuple[tuple[str, str, str], ...] = (
    ("PNEUMA_APP_PG_PORT", "pg_dsn", "Postgres"),
    ("PNEUMA_APP_QDRANT_PORT", "qdrant_url", "Qdrant"),
    ("PNEUMA_APP_MEILI_PORT", "meili_url", "Meilisearch"),
    ("PNEUMA_APP_RUSTFS_PORT", "media_s3_endpoint_url", "the media store"),
)


def read_env_file(path: Path) -> dict[str, str]:
    """`KEY=value` lines of a `.env`, or `{}` when there is none.

    Deliberately the shim's own parser and not a dotenv library: what this needs to know is
    whether a project stated its ports, and a file it cannot read states nothing.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return {}
    values: dict[str, str] = {}
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def project_isolation_problems(
    settings,  # noqa: ANN001
    *,
    environ: Mapping[str, str] | None = None,
    project: Path | str | None = None,
) -> list[str]:
    """Every way the resolved settings point somewhere other than this project's own stack.

    Empty when there is no project to speak of — a directory with no `PNEUMA_APP_*` ports
    stated is not a generated project, and the framework's own development use is exactly
    that case.
    """
    root = Path(project or ".").expanduser().resolve()
    env: dict[str, str] = dict(read_env_file(root / ENV_FILENAME))
    env.update(environ if environ is not None else os.environ)
    if not any(env.get(name, "").strip() for name, _, _ in _PORTED):
        return []

    problems: list[str] = []
    for name, field, label in _PORTED:
        port = env.get(name, "").strip()
        if not port:
            continue
        value = str(getattr(settings, field, "") or "")
        if f":{port}" in value:
            continue
        problems.append(
            f"{label}: this project's {name} is {port}, but {field} resolves to {value!r}"
        )
    canonical = Path(str(getattr(settings, "canonical_root", "") or ".")).expanduser().resolve()
    if root not in canonical.parents and canonical != root:
        problems.append(
            f"the canonical library: canonical_root resolves to {canonical}, "
            f"which is outside this project ({root})"
        )
    return problems


def isolation_refusal(problems: list[str]) -> str:
    """The refusal a caller prints — what is wrong, and the one thing that fixes it."""
    return (
        "error: this project's own stack is not what these settings reach, so `pkc` refuses "
        "to run rather than read or write some other library on this machine:\n  - "
        + "\n  - ".join(problems)
        + "\n\nThe project's `.env` must state its own connection settings "
        "(PNEUMA_KNOWLEDGE_PG_DSN, _QDRANT_URL, _QDRANT_COLLECTION, _MEILI_URL, _MEILI_KEY, "
        "_CANONICAL_ROOT, _MEDIA_S3_ENDPOINT_URL and the media credentials) matching the "
        "PNEUMA_APP_* ports beside them. A project generated by `scaffold/init.py` carries "
        "them; one generated before this check did not, and re-running the generator — or "
        "copying those lines from `.env.example` — is the fix."
    )
