#!/usr/bin/env bash
# Experience pneuma-knowledge in one command: check prerequisites → start the stack →
# initialize → ingest → compile → demo questions (when the project ships any) → print the
# knowledge-base overview. Safe to run repeatedly (idempotent).
# CI / non-interactive environments: ./start.sh --yes (every confirmation takes the default).
set -euo pipefail
cd "$(dirname "$0")"

# Leave no __pycache__ in the project directory.
export PYTHONDONTWRITEBYTECODE=1
rm -rf __pycache__

missing=()
command -v docker >/dev/null 2>&1 || missing+=("docker (https://docs.docker.com/get-docker/)")
command -v uv >/dev/null 2>&1 || missing+=("uv (https://docs.astral.sh/uv/)")
if [ ${#missing[@]} -gt 0 ]; then
  echo "Missing prerequisites:"
  printf '  - %s\n' "${missing[@]}"
  exit 1
fi

if [ ! -f .env ]; then
  if [ -f .env.example ]; then
    cp .env.example .env
    echo "Recreated .env from .env.example. Fill OPENROUTER_API_KEY, then run ./start.sh again."
  else
    echo ".env not found. This project is meant to be generated by the framework repo's"
    echo "scaffold/init.py (which writes .env and .env.example)."
  fi
  exit 1
fi

unfilled=()
for key in OPENROUTER_API_KEY PNEUMA_APP_COMPILE_MODEL PNEUMA_APP_RECALL_MODEL PNEUMA_APP_EMBEDDING_MODEL; do
  value="$(grep -E "^${key}=" .env | head -n1 | cut -d= -f2- | tr -d '"' | tr -d "'" | tr -d '[:space:]' || true)"
  [ -n "$value" ] || unfilled+=("$key")
done
if [ ${#unfilled[@]} -gt 0 ]; then
  echo "These .env entries are still empty:"
  printf '  %s=\n' "${unfilled[@]}"
  echo "Fill them in, then run ./start.sh again."
  exit 1
fi

# Confirm the framework repository is reachable before starting anything: when the project
# lives outside the repository and .env lost PNEUMA_APP_FRAMEWORK_REPO, say so here rather
# than failing halfway through the run.
./app.py preflight || exit 1

exec ./app.py demo "$@"
