#!/usr/bin/env bash
# Validate and build your material. Pass a material directory to override my-data/.
set -euo pipefail
cd "$(dirname "$0")"

# Leave no __pycache__ in the project directory.
export PYTHONDONTWRITEBYTECODE=1
rm -rf __pycache__

missing=()
command -v docker >/dev/null 2>&1 || missing+=("docker (https://docs.docker.com/get-docker/)")
command -v uv >/dev/null 2>&1 || missing+=("uv (https://docs.astral.sh/uv/)")
if [ ${#missing[@]} -gt 0 ]; then
  echo "Missing prerequisites:"
  printf '  - %s\n' "${missing[@]}"
  exit 1
fi

if [ ! -f .env ]; then
  if [ -f .env.example ]; then
    cp .env.example .env
    echo "Recreated .env from .env.example. Fill OPENROUTER_API_KEY, then run ./start.sh again."
  else
    echo ".env not found. This project is meant to be generated by the framework repo's"
    echo "scaffold/init.py (which writes .env and .env.example)."
  fi
  exit 1
fi

# The key is the only thing a person has to fill in by hand. Models are strategy and live in
# engine/engine.yaml, where app.py checks them and names what is missing.
key="$(grep -E "^OPENROUTER_API_KEY=" .env | head -n1 | cut -d= -f2- | tr -d '"' | tr -d "'" | tr -d '[:space:]' || true)"
if [ -z "$key" ]; then
  echo "OPENROUTER_API_KEY= in .env is still empty."
  echo "Fill it in (https://openrouter.ai/keys), then run ./start.sh again."
  exit 1
fi

if [ ! -f engine/engine.yaml ]; then
  echo "engine/ is missing or incomplete: this project's strategy, compile contract and"
  echo "profile all live there. Regenerate the project with the framework repo's"
  echo "scaffold/init.py, or restore engine/ from its own git history."
  exit 1
fi

# Confirm the framework repository is reachable before starting anything: when the project
# lives outside the repository and .env lost PNEUMA_APP_FRAMEWORK_REPO, say so here rather
# than failing halfway through the run.
./app.py preflight || exit 1

exec ./app.py build "$@"
